name: siraf3
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.3+1049606

environment:
  sdk: '>=2.17.0 <3.3.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  shared_preferences: ^2.0.13
  file_picker: ^4.4.0
  dropdown_button2: ^1.2.5
  persian_datetime_picker: ^2.6.0
  flutter_bloc: ^8.0.1
  flutter_spinkit: ^5.1.0
  carousel_slider: ^4.0.0
  dio: ^4.0.6
  location: ^4.3.0
  photo_view: ^0.13.0
  persian_number_utility: ^1.1.1
  url_launcher: ^6.1.2
  webview_flutter: ^3.0.4
  video_player: ^2.0.0
  flutter_share: ^2.0.0
  uni_links: ^0.5.1
  modal_bottom_sheet: ^2.1.2
  currency_text_input_formatter: ^2.1.7
  countup: ^0.1.4
  dotted_border: ^2.0.0+2
  lottie: ^1.3.0
  flutter_map: 1.1.0
  flutter_map_marker_cluster: any
  http_proxy: ^1.2.0
  flutter_multi_formatter: ^2.5.8
  mask_text_input_formatter: ^2.4.0
  mask_input_formatter: ^0.0.3
  typicons_flutter: ^0.5.0
  package_info_plus: ^1.4.2
  skeletons: ^0.0.3
  flutter_rating_bar: ^4.0.1
  flutter_octicons: ^0.21.0
  font_awesome_flutter: ^10.3.0
  dotted_line: ^3.1.0
  video_thumbnail: ^0.5.3
  platform: ^3.1.0
  path_provider: ^2.0.11
  sqflite: ^2.2.4+1
  badges: ^3.0.2
  auto_direction: ^0.0.6
  flutter_switch: ^0.3.2
  provider: ^6.0.5
  change_app_package_name: ^1.1.0
  syncfusion_flutter_charts: ^20.4.53
  introduction_screen: ^3.1.4
  simple_circular_progress_bar: ^1.0.2
  percent_indicator: ^4.2.3
  permission_handler: ^10.2.0
  crypto: ^3.0.3
  audioplayers: ^4.1.0
  open_file: ^3.2.1
  shamsi_date: ^1.0.1
  firebase: ^9.0.3
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^8.2.0
  dart_amqp: ^0.2.5
  logger: ^1.4.0
  flutter_staggered_grid_view: ^0.6.2
  record: ^4.4.4
  cached_network_image: ^3.2.3
  linkwell: ^2.0.6
  intl: ^0.17.0
  image_size_getter: ^2.1.2
  flutter_sound: ^9.2.13
  emoji_picker_flutter: ^1.6.1
  flutter_keyboard_size: ^1.0.1
  fleather: ^1.7.0
  scrollable_positioned_list: ^0.3.8
  image_picker: ^1.0.1
  flutter_image_compress: ^2.0.4
  pretty_qr_code: ^2.0.3
  screenshot: ^1.3.0
  share_plus: ^4.5.3
  flutter_launcher_icons: ^0.13.1
  switcher_button: ^0.0.4
  video_compress: ^3.1.2
  fluttertoast: ^8.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 20

flutter:

  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/sounds/

  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir.ttf
    - family: KalamehBlack
      fonts:
        - asset: assets/fonts/KALAMEH_BLACK.TTF
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSansXFaNumRegular.TTF
    - family: IranSansBold
      fonts:
        - asset: assets/fonts/IRANSansXFaNumBold.TTF
    - family: IranSansLight
      fonts:
        - asset: assets/fonts/IRANSansXFaNumLight.TTF
    - family: IranSansBlack
      fonts:
        - asset: assets/fonts/IRANSansXFaNumBlack.TTF
    - family: IranSansMedium
      fonts:
        - asset: assets/fonts/IRANSansXFaNumMedium.TTF

flutter_launcher_name:
  name: "سیراف"
